f = open('SETinstructionexamplecompiled.tau', 'w')
f.write('Indeterminant;0.5')
f.write(chr(0))
f.write(''.join([chr(0)]*2))
f.write(chr(7))
f.write(''.join([chr(0)]*7))
f.write(chr(1))
f.write(''.join([chr(0)]*7))
f.write(chr(2))
f.write(''.join([chr(0)]*7))
f.write(chr(3))
f.write(''.join([chr(0)]*7))
f.write(chr(4))
f.write(''.join([chr(0)]*7))
f.write(chr(5))
f.write(''.join([chr(0)]*7))
f.write(chr(6))
f.close()
